import * as fs from "fs";
import * as path from "path";
import type { SeedPlayerGameStats } from "@nbbl/shared";

export function serializePlayerStatsSeed(
  data: Record<string, SeedPlayerGameStats>
): string {
  const json = JSON.stringify(data, null, 2);
  return `// Auto-generated by simulateTournament — do not edit manually
import type { SeedPlayerGameStats } from "@nbbl/shared";

export const CIRCUIT1_PLAYER_STATS: Record<string, SeedPlayerGameStats> = ${json};
`;
}

export function syncPlayerStatsToSeedFile(
  data: Record<string, SeedPlayerGameStats>
): boolean {
  if (!process.env.FIRESTORE_EMULATOR_HOST) {
    return false;
  }

  const seedDir = path.resolve(__dirname, "../../../src/scripts/seed-data");
  const dataPath = path.join(seedDir, "circuit1-player-stats.ts");
  fs.writeFileSync(dataPath, serializePlayerStatsSeed(data), "utf-8");
  return true;
}
