import * as fs from "fs";
import * as path from "path";
import type { SeedTeamGameStats } from "@nbbl/shared";

export function serializeTeamStatsSeed(
  data: Record<string, SeedTeamGameStats>
): string {
  const json = JSON.stringify(data, null, 2);
  return `// Auto-generated by simulateTournament — do not edit manually
import type { SeedTeamGameStats } from "@nbbl/shared";

export const CIRCUIT1_TEAM_STATS: Record<string, SeedTeamGameStats> = ${json};
`;
}

export function syncTeamStatsToSeedFile(
  data: Record<string, SeedTeamGameStats>
): boolean {
  if (!process.env.FIRESTORE_EMULATOR_HOST) {
    return false;
  }

  const seedDir = path.resolve(__dirname, "../../../src/scripts/seed-data");
  const dataPath = path.join(seedDir, "circuit1-team-stats.ts");
  fs.writeFileSync(dataPath, serializeTeamStatsSeed(data), "utf-8");
  return true;
}
