// Auto-generated by simulateTournament — do not edit manually
import type { SeedTeamGameStats } from "@nbbl/shared";

export const CIRCUIT1_TEAM_STATS: Record<string, SeedTeamGameStats> = {
  "team_boys_arizona_elite": {
    "seasonStats": {
      "gamesPlayed": 10,
      "wins": 3,
      "losses": 7
    },
    "pointsPerGame": 17.9,
    "fieldGoalPct": 0.437,
    "threePointPct": 0.211
  },
  "team_boys_desert_force": {
    "seasonStats": {
      "gamesPlayed": 10,
      "wins": 4,
      "losses": 6
    },
    "pointsPerGame": 18.4,
    "fieldGoalPct": 0.426,
    "threePointPct": 0.218
  },
  "team_boys_phoenix_storm": {
    "seasonStats": {
      "gamesPlayed": 11,
      "wins": 8,
      "losses": 3
    },
    "pointsPerGame": 21.5,
    "fieldGoalPct": 0.423,
    "threePointPct": 0.262
  },
  "team_boys_valley_select": {
    "seasonStats": {
      "gamesPlayed": 11,
      "wins": 6,
      "losses": 5
    },
    "pointsPerGame": 19.6,
    "fieldGoalPct": 0.451,
    "threePointPct": 0.189
  },
  "team_girls_arizona_flight": {
    "seasonStats": {
      "gamesPlayed": 11,
      "wins": 9,
      "losses": 2
    },
    "pointsPerGame": 20.8,
    "fieldGoalPct": 0.437,
    "threePointPct": 0.179
  },
  "team_girls_desert_legacy": {
    "seasonStats": {
      "gamesPlayed": 11,
      "wins": 7,
      "losses": 4
    },
    "pointsPerGame": 19.5,
    "fieldGoalPct": 0.443,
    "threePointPct": 0.192
  },
  "team_girls_phoenix_queens": {
    "seasonStats": {
      "gamesPlayed": 10,
      "wins": 1,
      "losses": 9
    },
    "pointsPerGame": 16.5,
    "fieldGoalPct": 0.422,
    "threePointPct": 0.166
  },
  "team_girls_valley_united": {
    "seasonStats": {
      "gamesPlayed": 10,
      "wins": 4,
      "losses": 6
    },
    "pointsPerGame": 18.4,
    "fieldGoalPct": 0.458,
    "threePointPct": 0.23
  }
};
